export default {
    GET_ARTICLE_LIST: 'GET_ARTICLE_LIST',
    GET_COMMENTS: 'GET_COMMENTS',
    GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL',
    RESET_ARTICLE_DETAIL: 'RESET_ARTICLE_DETAIL',
    RESET_COMMENTS: 'RESET_COMMENTS',
    ADD_COMMENT: 'ADD_COMMENT',
    ADD_COMMENT_LOADING: 'ADD_COMMENT_LOADING',
    ADD_COMMENT_LIKED: 'ADD_COMMENT_LIKED',
    ADD_COMMENT_DISLIKED: 'ADD_COMMENT_DISLIKED',
    ADD_ARTICLE: 'ADD_ARTICLE',
    ADD_COMMENT_DONE: 'ADD_COMMENT_DONE'
}